[package]
name = "primitives"
description = "Primitives for the Neuroweb runtime"
authors = { workspace = true }
edition = "2021"
version = "0.1.0"

[dependencies]
codec = { workspace = true }
scale-info = { workspace = true }
frame-support = { workspace = true }
sp-runtime = { workspace = true }
xcm = { workspace = true }
serde = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "frame-support/std",
    "sp-runtime/std",
    "xcm/std",
    "serde/std",
]
