// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.


//! Autogenerated weights for `pallet_assets_foreign`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-08-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ns3111125`, CPU: `Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// target/release/neuroweb
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template=scripts/pallet-weight-template.hbs
// --pallet=pallet_assets_foreign
// --output=weights.rs
// --extrinsic=*

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use crate::*;

/// Weights for `pallet_assets_foreign` using the Neuroweb node and recommended hardware.
pub struct NeurowebWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_assets::WeightInfo for NeurowebWeight<T> {
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn create() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `107`
        //  Estimated: `4273`
        // Minimum execution time: 32_973_000 picoseconds.
        Weight::from_parts(33_283_000, 4273)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    fn force_create() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `4`
        //  Estimated: `4273`
        // Minimum execution time: 14_720_000 picoseconds.
        Weight::from_parts(15_217_000, 4273)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    fn start_destroy() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `276`
        //  Estimated: `4273`
        // Minimum execution time: 15_143_000 picoseconds.
        Weight::from_parts(15_415_000, 4273)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Account` (r:657 w:656)
    /// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:656 w:656)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// The range of component `c` is `[0, 656]`.
    fn destroy_accounts(c: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `132 + c * (208 ±0)`
        //  Estimated: `4273 + c * (3207 ±0)`
        // Minimum execution time: 20_638_000 picoseconds.
        Weight::from_parts(20_812_000, 4273)
            // Standard Error: 8_542
            .saturating_add(Weight::from_parts(14_166_009, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(c.into())))
            .saturating_add(T::DbWeight::get().writes(1_u64))
            .saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(c.into())))
            .saturating_add(Weight::from_parts(0, 3207).saturating_mul(c.into()))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Approvals` (r:657 w:656)
    /// Proof: `ForeignAssets::Approvals` (`max_values`: None, `max_size`: Some(746), added: 3221, mode: `MaxEncodedLen`)
    /// The range of component `a` is `[0, 656]`.
    fn destroy_approvals(a: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `364 + a * (86 ±0)`
        //  Estimated: `4273 + a * (3221 ±0)`
        // Minimum execution time: 21_156_000 picoseconds.
        Weight::from_parts(21_434_000, 4273)
            // Standard Error: 5_888
            .saturating_add(Weight::from_parts(16_435_344, 0).saturating_mul(a.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(a.into())))
            .saturating_add(T::DbWeight::get().writes(1_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(a.into())))
            .saturating_add(Weight::from_parts(0, 3221).saturating_mul(a.into()))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Metadata` (r:1 w:0)
    /// Proof: `ForeignAssets::Metadata` (`max_values`: None, `max_size`: Some(738), added: 3213, mode: `MaxEncodedLen`)
    fn finish_destroy() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `242`
        //  Estimated: `4273`
        // Minimum execution time: 17_889_000 picoseconds.
        Weight::from_parts(18_208_000, 4273)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Account` (r:1 w:1)
    /// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
    fn mint() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `242`
        //  Estimated: `4273`
        // Minimum execution time: 29_497_000 picoseconds.
        Weight::from_parts(30_032_000, 4273)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Account` (r:1 w:1)
    /// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
    fn burn() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `350`
        //  Estimated: `4273`
        // Minimum execution time: 37_897_000 picoseconds.
        Weight::from_parts(38_242_000, 4273)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Account` (r:2 w:2)
    /// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn transfer() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `422`
        //  Estimated: `7404`
        // Minimum execution time: 53_349_000 picoseconds.
        Weight::from_parts(53_822_000, 7404)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Account` (r:2 w:2)
    /// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn transfer_keep_alive() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `422`
        //  Estimated: `7404`
        // Minimum execution time: 47_756_000 picoseconds.
        Weight::from_parts(48_389_000, 7404)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Account` (r:2 w:2)
    /// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn force_transfer() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `422`
        //  Estimated: `7404`
        // Minimum execution time: 53_051_000 picoseconds.
        Weight::from_parts(53_758_000, 7404)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:0)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Account` (r:1 w:1)
    /// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
    fn freeze() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `350`
        //  Estimated: `4273`
        // Minimum execution time: 19_589_000 picoseconds.
        Weight::from_parts(19_914_000, 4273)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:0)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Account` (r:1 w:1)
    /// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
    fn thaw() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `350`
        //  Estimated: `4273`
        // Minimum execution time: 19_486_000 picoseconds.
        Weight::from_parts(19_791_000, 4273)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    fn freeze_asset() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `276`
        //  Estimated: `4273`
        // Minimum execution time: 14_911_000 picoseconds.
        Weight::from_parts(15_242_000, 4273)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    fn thaw_asset() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `276`
        //  Estimated: `4273`
        // Minimum execution time: 14_970_000 picoseconds.
        Weight::from_parts(15_262_000, 4273)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Metadata` (r:1 w:0)
    /// Proof: `ForeignAssets::Metadata` (`max_values`: None, `max_size`: Some(738), added: 3213, mode: `MaxEncodedLen`)
    fn transfer_ownership() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `242`
        //  Estimated: `4273`
        // Minimum execution time: 18_403_000 picoseconds.
        Weight::from_parts(18_824_000, 4273)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    fn set_team() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `242`
        //  Estimated: `4273`
        // Minimum execution time: 15_982_000 picoseconds.
        Weight::from_parts(16_328_000, 4273)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:0)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Metadata` (r:1 w:1)
    /// Proof: `ForeignAssets::Metadata` (`max_values`: None, `max_size`: Some(738), added: 3213, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[0, 50]`.
    /// The range of component `s` is `[0, 50]`.
    fn set_metadata(n: u32, _s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `242`
        //  Estimated: `4273`
        // Minimum execution time: 33_249_000 picoseconds.
        Weight::from_parts(34_275_062, 4273)
            // Standard Error: 476
            .saturating_add(Weight::from_parts(71, 0).saturating_mul(n.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:0)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Metadata` (r:1 w:1)
    /// Proof: `ForeignAssets::Metadata` (`max_values`: None, `max_size`: Some(738), added: 3213, mode: `MaxEncodedLen`)
    fn clear_metadata() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `406`
        //  Estimated: `4273`
        // Minimum execution time: 34_102_000 picoseconds.
        Weight::from_parts(34_514_000, 4273)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:0)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Metadata` (r:1 w:1)
    /// Proof: `ForeignAssets::Metadata` (`max_values`: None, `max_size`: Some(738), added: 3213, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[0, 50]`.
    /// The range of component `s` is `[0, 50]`.
    fn force_set_metadata(n: u32, s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `81`
        //  Estimated: `4273`
        // Minimum execution time: 16_538_000 picoseconds.
        Weight::from_parts(17_096_983, 4273)
            // Standard Error: 344
            .saturating_add(Weight::from_parts(68, 0).saturating_mul(n.into()))
            // Standard Error: 344
            .saturating_add(Weight::from_parts(1_342, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:0)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Metadata` (r:1 w:1)
    /// Proof: `ForeignAssets::Metadata` (`max_values`: None, `max_size`: Some(738), added: 3213, mode: `MaxEncodedLen`)
    fn force_clear_metadata() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `406`
        //  Estimated: `4273`
        // Minimum execution time: 32_953_000 picoseconds.
        Weight::from_parts(33_430_000, 4273)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    fn force_asset_status() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `242`
        //  Estimated: `4273`
        // Minimum execution time: 14_587_000 picoseconds.
        Weight::from_parts(14_811_000, 4273)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Approvals` (r:1 w:1)
    /// Proof: `ForeignAssets::Approvals` (`max_values`: None, `max_size`: Some(746), added: 3221, mode: `MaxEncodedLen`)
    fn approve_transfer() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `276`
        //  Estimated: `4273`
        // Minimum execution time: 37_440_000 picoseconds.
        Weight::from_parts(38_077_000, 4273)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Approvals` (r:1 w:1)
    /// Proof: `ForeignAssets::Approvals` (`max_values`: None, `max_size`: Some(746), added: 3221, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Account` (r:2 w:2)
    /// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn transfer_approved() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `592`
        //  Estimated: `7404`
        // Minimum execution time: 77_902_000 picoseconds.
        Weight::from_parts(78_438_000, 7404)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Approvals` (r:1 w:1)
    /// Proof: `ForeignAssets::Approvals` (`max_values`: None, `max_size`: Some(746), added: 3221, mode: `MaxEncodedLen`)
    fn cancel_approval() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `446`
        //  Estimated: `4273`
        // Minimum execution time: 40_668_000 picoseconds.
        Weight::from_parts(40_940_000, 4273)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Approvals` (r:1 w:1)
    /// Proof: `ForeignAssets::Approvals` (`max_values`: None, `max_size`: Some(746), added: 3221, mode: `MaxEncodedLen`)
    fn force_cancel_approval() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `446`
        //  Estimated: `4273`
        // Minimum execution time: 40_976_000 picoseconds.
        Weight::from_parts(41_512_000, 4273)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    fn set_min_balance() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `242`
        //  Estimated: `4273`
        // Minimum execution time: 16_264_000 picoseconds.
        Weight::from_parts(16_576_000, 4273)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `ForeignAssets::Account` (r:1 w:1)
    /// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn touch() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `345`
        //  Estimated: `4273`
        // Minimum execution time: 40_493_000 picoseconds.
        Weight::from_parts(41_045_000, 4273)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `ForeignAssets::Account` (r:1 w:1)
    /// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    fn touch_other() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `242`
        //  Estimated: `4273`
        // Minimum execution time: 37_710_000 picoseconds.
        Weight::from_parts(38_059_000, 4273)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `ForeignAssets::Account` (r:1 w:1)
    /// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn refund() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `471`
        //  Estimated: `4273`
        // Minimum execution time: 38_167_000 picoseconds.
        Weight::from_parts(38_687_000, 4273)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `ForeignAssets::Account` (r:1 w:1)
    /// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Asset` (r:1 w:1)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    fn refund_other() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `401`
        //  Estimated: `4273`
        // Minimum execution time: 35_834_000 picoseconds.
        Weight::from_parts(36_266_000, 4273)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `ForeignAssets::Asset` (r:1 w:0)
    /// Proof: `ForeignAssets::Asset` (`max_values`: None, `max_size`: Some(808), added: 3283, mode: `MaxEncodedLen`)
    /// Storage: `ForeignAssets::Account` (r:1 w:1)
    /// Proof: `ForeignAssets::Account` (`max_values`: None, `max_size`: Some(732), added: 3207, mode: `MaxEncodedLen`)
    fn block() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `350`
        //  Estimated: `4273`
        // Minimum execution time: 19_449_000 picoseconds.
        Weight::from_parts(19_868_000, 4273)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}
