// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.


//! Autogenerated weights for `pallet_collator_selection`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-08-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ns3111125`, CPU: `Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// target/release/neuroweb
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template=scripts/pallet-weight-template.hbs
// --pallet=pallet_collator_selection
// --output=weights.rs
// --extrinsic=set_invulnerables,remove_invulnerable,set_desired_candidates,note_author

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use crate::*;

/// Weights for `pallet_collator_selection` using the Neuroweb node and recommended hardware.
pub struct NeurowebWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_collator_selection::WeightInfo for NeurowebWeight<T> {
    /// Storage: `Session::NextKeys` (r:100 w:0)
    /// Proof: `Session::NextKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `CollatorSelection::Invulnerables` (r:0 w:1)
    /// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
    /// The range of component `b` is `[1, 100]`.
    fn set_invulnerables(b: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `215 + b * (78 ±0)`
        //  Estimated: `1204 + b * (2554 ±0)`
        // Minimum execution time: 15_295_000 picoseconds.
        Weight::from_parts(15_467_322, 1204)
            // Standard Error: 3_459
            .saturating_add(Weight::from_parts(3_246_098, 0).saturating_mul(b.into()))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(b.into())))
            .saturating_add(T::DbWeight::get().writes(1_u64))
            .saturating_add(Weight::from_parts(0, 2554).saturating_mul(b.into()))
    }
    /// Storage: `Session::NextKeys` (r:1 w:0)
    /// Proof: `Session::NextKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `CollatorSelection::Invulnerables` (r:1 w:1)
    /// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(1601), added: 2096, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::CandidateList` (r:1 w:1)
    /// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(961), added: 1456, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// The range of component `b` is `[1, 49]`.
    /// The range of component `c` is `[1, 19]`.
    fn add_invulnerable(b: u32, c: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `959 + b * (40 ±0) + c * (48 ±0)`
        //  Estimated: `4439 + b * (42 ±0) + c * (47 ±0)`
        // Minimum execution time: 55_157_000 picoseconds.
        Weight::from_parts(54_833_233, 4439)
            // Standard Error: 1_205
            .saturating_add(Weight::from_parts(114_232, 0).saturating_mul(b.into()))
            // Standard Error: 3_176
            .saturating_add(Weight::from_parts(32_087, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
            .saturating_add(Weight::from_parts(0, 42).saturating_mul(b.into()))
            .saturating_add(Weight::from_parts(0, 47).saturating_mul(c.into()))
    }
    /// Storage: `CollatorSelection::CandidateList` (r:1 w:0)
    /// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(48002), added: 48497, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::Invulnerables` (r:1 w:1)
    /// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(3202), added: 3697, mode: `MaxEncodedLen`)
    /// The range of component `b` is `[4, 100]`.
    fn remove_invulnerable(b: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `153 + b * (32 ±0)`
        //  Estimated: `49487`
        // Minimum execution time: 15_488_000 picoseconds.
        Weight::from_parts(16_123_265, 49487)
            // Standard Error: 401
            .saturating_add(Weight::from_parts(32_919, 0).saturating_mul(b.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `CollatorSelection::DesiredCandidates` (r:0 w:1)
    /// Proof: `CollatorSelection::DesiredCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    fn set_desired_candidates() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 8_005_000 picoseconds.
        Weight::from_parts(8_122_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `CollatorSelection::CandidacyBond` (r:1 w:1)
    /// Proof: `CollatorSelection::CandidacyBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::CandidateList` (r:1 w:1)
    /// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(961), added: 1456, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:20 w:20)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::LastAuthoredBlock` (r:0 w:20)
    /// Proof: `CollatorSelection::LastAuthoredBlock` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// The range of component `c` is `[0, 20]`.
    /// The range of component `k` is `[0, 20]`.
    fn set_candidacy_bond(c: u32, k: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0 + c * (179 ±0) + k * (128 ±0)`
        //  Estimated: `3593 + c * (848 ±30) + k * (848 ±30)`
        // Minimum execution time: 15_061_000 picoseconds.
        Weight::from_parts(15_453_000, 3593)
            // Standard Error: 189_239
            .saturating_add(Weight::from_parts(6_539_492, 0).saturating_mul(c.into()))
            // Standard Error: 189_239
            .saturating_add(Weight::from_parts(6_352_758, 0).saturating_mul(k.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(k.into())))
            .saturating_add(Weight::from_parts(0, 848).saturating_mul(c.into()))
            .saturating_add(Weight::from_parts(0, 848).saturating_mul(k.into()))
    }
    /// Storage: `CollatorSelection::CandidacyBond` (r:1 w:0)
    /// Proof: `CollatorSelection::CandidacyBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::CandidateList` (r:1 w:1)
    /// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(961), added: 1456, mode: `MaxEncodedLen`)
    /// The range of component `c` is `[3, 20]`.
    fn update_bond(c: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `495 + c * (48 ±0)`
        //  Estimated: `2446`
        // Minimum execution time: 36_287_000 picoseconds.
        Weight::from_parts(37_067_037, 2446)
            // Standard Error: 4_934
            .saturating_add(Weight::from_parts(62_689, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `CollatorSelection::CandidateList` (r:1 w:1)
    /// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(961), added: 1456, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::Invulnerables` (r:1 w:0)
    /// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(1601), added: 2096, mode: `MaxEncodedLen`)
    /// Storage: `Session::NextKeys` (r:1 w:0)
    /// Proof: `Session::NextKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `CollatorSelection::CandidacyBond` (r:1 w:0)
    /// Proof: `CollatorSelection::CandidacyBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::LastAuthoredBlock` (r:0 w:1)
    /// Proof: `CollatorSelection::LastAuthoredBlock` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// The range of component `c` is `[1, 19]`.
    fn register_as_candidate(c: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `715 + c * (61 ±0)`
        //  Estimated: `4180 + c * (61 ±0)`
        // Minimum execution time: 52_432_000 picoseconds.
        Weight::from_parts(53_439_429, 4180)
            // Standard Error: 1_956
            .saturating_add(Weight::from_parts(159_404, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
            .saturating_add(Weight::from_parts(0, 61).saturating_mul(c.into()))
    }
    /// Storage: `CollatorSelection::Invulnerables` (r:1 w:0)
    /// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(1601), added: 2096, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::CandidacyBond` (r:1 w:0)
    /// Proof: `CollatorSelection::CandidacyBond` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    /// Storage: `Session::NextKeys` (r:1 w:0)
    /// Proof: `Session::NextKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// Storage: `CollatorSelection::CandidateList` (r:1 w:1)
    /// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(961), added: 1456, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::LastAuthoredBlock` (r:0 w:2)
    /// Proof: `CollatorSelection::LastAuthoredBlock` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// The range of component `c` is `[3, 20]`.
    fn take_candidate_slot(c: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `815 + c * (61 ±0)`
        //  Estimated: `4280 + c * (61 ±0)`
        // Minimum execution time: 71_194_000 picoseconds.
        Weight::from_parts(72_004_333, 4280)
            // Standard Error: 2_193
            .saturating_add(Weight::from_parts(136_326, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
            .saturating_add(Weight::from_parts(0, 61).saturating_mul(c.into()))
    }
    /// Storage: `CollatorSelection::CandidateList` (r:1 w:1)
    /// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(961), added: 1456, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::Invulnerables` (r:1 w:0)
    /// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(1601), added: 2096, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::LastAuthoredBlock` (r:0 w:1)
    /// Proof: `CollatorSelection::LastAuthoredBlock` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// The range of component `c` is `[3, 20]`.
    fn leave_intent(c: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `507 + c * (48 ±0)`
        //  Estimated: `3086`
        // Minimum execution time: 39_072_000 picoseconds.
        Weight::from_parts(39_673_539, 3086)
            // Standard Error: 2_037
            .saturating_add(Weight::from_parts(96_410, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `System::Account` (r:2 w:2)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::LastAuthoredBlock` (r:0 w:1)
    /// Proof: `CollatorSelection::LastAuthoredBlock` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    fn note_author() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `155`
        //  Estimated: `6196`
        // Minimum execution time: 51_839_000 picoseconds.
        Weight::from_parts(52_398_000, 6196)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `CollatorSelection::CandidateList` (r:1 w:0)
    /// Proof: `CollatorSelection::CandidateList` (`max_values`: Some(1), `max_size`: Some(961), added: 1456, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::LastAuthoredBlock` (r:20 w:0)
    /// Proof: `CollatorSelection::LastAuthoredBlock` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::Invulnerables` (r:1 w:0)
    /// Proof: `CollatorSelection::Invulnerables` (`max_values`: Some(1), `max_size`: Some(1601), added: 2096, mode: `MaxEncodedLen`)
    /// Storage: `CollatorSelection::DesiredCandidates` (r:1 w:0)
    /// Proof: `CollatorSelection::DesiredCandidates` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:18 w:18)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// The range of component `r` is `[1, 20]`.
    /// The range of component `c` is `[1, 20]`.
    fn new_session(r: u32, c: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `466 + c * (98 ±0) + r * (134 ±0)`
        //  Estimated: `3086 + c * (2519 ±2) + r * (2571 ±3)`
        // Minimum execution time: 26_984_000 picoseconds.
        Weight::from_parts(27_256_000, 3086)
            // Standard Error: 320_759
            .saturating_add(Weight::from_parts(15_247_489, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(c.into())))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(c.into())))
            .saturating_add(Weight::from_parts(0, 2519).saturating_mul(c.into()))
            .saturating_add(Weight::from_parts(0, 2571).saturating_mul(r.into()))
    }
}
