// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.


//! Autogenerated weights for `pallet_assets`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2025-08-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ns3111125`, CPU: `Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// target/release/neuroweb
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --wasm-execution=compiled
// --heap-pages=4096
// --template=scripts/pallet-weight-template.hbs
// --pallet=pallet_assets
// --output=weights.rs
// --extrinsic=*

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;
use crate::*;

/// Weights for `pallet_assets` using the Neuroweb node and recommended hardware.
pub struct NeurowebWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_assets::WeightInfo for NeurowebWeight<T> {
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn create() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `146`
        //  Estimated: `3687`
        // Minimum execution time: 30_015_000 picoseconds.
        Weight::from_parts(30_602_000, 3687)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    fn force_create() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `6`
        //  Estimated: `3687`
        // Minimum execution time: 12_771_000 picoseconds.
        Weight::from_parts(13_233_000, 3687)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    fn start_destroy() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `289`
        //  Estimated: `3687`
        // Minimum execution time: 13_353_000 picoseconds.
        Weight::from_parts(13_596_000, 3687)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Account` (r:657 w:656)
    /// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:656 w:656)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// The range of component `c` is `[0, 656]`.
    fn destroy_accounts(c: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `156 + c * (208 ±0)`
        //  Estimated: `3687 + c * (2621 ±0)`
        // Minimum execution time: 18_478_000 picoseconds.
        Weight::from_parts(18_799_000, 3687)
            // Standard Error: 8_823
            .saturating_add(Weight::from_parts(13_459_234, 0).saturating_mul(c.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(c.into())))
            .saturating_add(T::DbWeight::get().writes(1_u64))
            .saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(c.into())))
            .saturating_add(Weight::from_parts(0, 2621).saturating_mul(c.into()))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Approvals` (r:657 w:656)
    /// Proof: `Assets::Approvals` (`max_values`: None, `max_size`: Some(160), added: 2635, mode: `MaxEncodedLen`)
    /// The range of component `a` is `[0, 656]`.
    fn destroy_approvals(a: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `389 + a * (86 ±0)`
        //  Estimated: `3687 + a * (2635 ±0)`
        // Minimum execution time: 18_945_000 picoseconds.
        Weight::from_parts(19_039_000, 3687)
            // Standard Error: 4_788
            .saturating_add(Weight::from_parts(15_564_160, 0).saturating_mul(a.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(a.into())))
            .saturating_add(T::DbWeight::get().writes(1_u64))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(a.into())))
            .saturating_add(Weight::from_parts(0, 2635).saturating_mul(a.into()))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Metadata` (r:1 w:0)
    /// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
    fn finish_destroy() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `255`
        //  Estimated: `3687`
        // Minimum execution time: 15_416_000 picoseconds.
        Weight::from_parts(15_858_000, 3687)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Account` (r:1 w:1)
    /// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
    fn mint() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `255`
        //  Estimated: `3687`
        // Minimum execution time: 26_952_000 picoseconds.
        Weight::from_parts(27_312_000, 3687)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Account` (r:1 w:1)
    /// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
    fn burn() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `375`
        //  Estimated: `3687`
        // Minimum execution time: 34_181_000 picoseconds.
        Weight::from_parts(34_646_000, 3687)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Account` (r:2 w:2)
    /// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn transfer() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `447`
        //  Estimated: `6232`
        // Minimum execution time: 48_292_000 picoseconds.
        Weight::from_parts(49_019_000, 6232)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Account` (r:2 w:2)
    /// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn transfer_keep_alive() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `447`
        //  Estimated: `6232`
        // Minimum execution time: 43_408_000 picoseconds.
        Weight::from_parts(43_682_000, 6232)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Account` (r:2 w:2)
    /// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn force_transfer() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `447`
        //  Estimated: `6232`
        // Minimum execution time: 48_537_000 picoseconds.
        Weight::from_parts(49_209_000, 6232)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:0)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Account` (r:1 w:1)
    /// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
    fn freeze() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `375`
        //  Estimated: `3687`
        // Minimum execution time: 17_699_000 picoseconds.
        Weight::from_parts(17_906_000, 3687)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:0)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Account` (r:1 w:1)
    /// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
    fn thaw() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `375`
        //  Estimated: `3687`
        // Minimum execution time: 17_763_000 picoseconds.
        Weight::from_parts(18_032_000, 3687)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    fn freeze_asset() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `289`
        //  Estimated: `3687`
        // Minimum execution time: 12_886_000 picoseconds.
        Weight::from_parts(13_268_000, 3687)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    fn thaw_asset() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `289`
        //  Estimated: `3687`
        // Minimum execution time: 12_992_000 picoseconds.
        Weight::from_parts(13_276_000, 3687)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Metadata` (r:1 w:0)
    /// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
    fn transfer_ownership() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `255`
        //  Estimated: `3687`
        // Minimum execution time: 15_682_000 picoseconds.
        Weight::from_parts(15_928_000, 3687)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    fn set_team() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `255`
        //  Estimated: `3687`
        // Minimum execution time: 13_762_000 picoseconds.
        Weight::from_parts(13_935_000, 3687)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:0)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Metadata` (r:1 w:1)
    /// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[0, 50]`.
    /// The range of component `s` is `[0, 50]`.
    fn set_metadata(n: u32, s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `255`
        //  Estimated: `3687`
        // Minimum execution time: 29_902_000 picoseconds.
        Weight::from_parts(30_836_133, 3687)
            // Standard Error: 453
            .saturating_add(Weight::from_parts(545, 0).saturating_mul(n.into()))
            // Standard Error: 453
            .saturating_add(Weight::from_parts(3_020, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:0)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Metadata` (r:1 w:1)
    /// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
    fn clear_metadata() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `431`
        //  Estimated: `3687`
        // Minimum execution time: 31_004_000 picoseconds.
        Weight::from_parts(31_329_000, 3687)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:0)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Metadata` (r:1 w:1)
    /// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
    /// The range of component `n` is `[0, 50]`.
    /// The range of component `s` is `[0, 50]`.
    fn force_set_metadata(n: u32, s: u32, ) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `94`
        //  Estimated: `3687`
        // Minimum execution time: 14_827_000 picoseconds.
        Weight::from_parts(15_595_129, 3687)
            // Standard Error: 300
            .saturating_add(Weight::from_parts(1_501, 0).saturating_mul(n.into()))
            // Standard Error: 300
            .saturating_add(Weight::from_parts(25, 0).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:0)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Metadata` (r:1 w:1)
    /// Proof: `Assets::Metadata` (`max_values`: None, `max_size`: Some(152), added: 2627, mode: `MaxEncodedLen`)
    fn force_clear_metadata() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `431`
        //  Estimated: `3687`
        // Minimum execution time: 30_658_000 picoseconds.
        Weight::from_parts(31_154_000, 3687)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    fn force_asset_status() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `255`
        //  Estimated: `3687`
        // Minimum execution time: 13_238_000 picoseconds.
        Weight::from_parts(13_571_000, 3687)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Approvals` (r:1 w:1)
    /// Proof: `Assets::Approvals` (`max_values`: None, `max_size`: Some(160), added: 2635, mode: `MaxEncodedLen`)
    fn approve_transfer() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `289`
        //  Estimated: `3687`
        // Minimum execution time: 34_852_000 picoseconds.
        Weight::from_parts(35_275_000, 3687)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Approvals` (r:1 w:1)
    /// Proof: `Assets::Approvals` (`max_values`: None, `max_size`: Some(160), added: 2635, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Account` (r:2 w:2)
    /// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn transfer_approved() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `629`
        //  Estimated: `6232`
        // Minimum execution time: 72_047_000 picoseconds.
        Weight::from_parts(72_635_000, 6232)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Approvals` (r:1 w:1)
    /// Proof: `Assets::Approvals` (`max_values`: None, `max_size`: Some(160), added: 2635, mode: `MaxEncodedLen`)
    fn cancel_approval() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `471`
        //  Estimated: `3687`
        // Minimum execution time: 37_364_000 picoseconds.
        Weight::from_parts(37_712_000, 3687)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Approvals` (r:1 w:1)
    /// Proof: `Assets::Approvals` (`max_values`: None, `max_size`: Some(160), added: 2635, mode: `MaxEncodedLen`)
    fn force_cancel_approval() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `471`
        //  Estimated: `3687`
        // Minimum execution time: 37_594_000 picoseconds.
        Weight::from_parts(38_054_000, 3687)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    fn set_min_balance() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `255`
        //  Estimated: `3687`
        // Minimum execution time: 14_587_000 picoseconds.
        Weight::from_parts(15_032_000, 3687)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: `Assets::Account` (r:1 w:1)
    /// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn touch() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `358`
        //  Estimated: `3687`
        // Minimum execution time: 36_815_000 picoseconds.
        Weight::from_parts(37_342_000, 3687)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `Assets::Account` (r:1 w:1)
    /// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    fn touch_other() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `255`
        //  Estimated: `3687`
        // Minimum execution time: 34_001_000 picoseconds.
        Weight::from_parts(34_489_000, 3687)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Assets::Account` (r:1 w:1)
    /// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:1 w:1)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn refund() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `496`
        //  Estimated: `3687`
        // Minimum execution time: 35_971_000 picoseconds.
        Weight::from_parts(36_443_000, 3687)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: `Assets::Account` (r:1 w:1)
    /// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Asset` (r:1 w:1)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    fn refund_other() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `426`
        //  Estimated: `3687`
        // Minimum execution time: 32_851_000 picoseconds.
        Weight::from_parts(33_410_000, 3687)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: `Assets::Asset` (r:1 w:0)
    /// Proof: `Assets::Asset` (`max_values`: None, `max_size`: Some(222), added: 2697, mode: `MaxEncodedLen`)
    /// Storage: `Assets::Account` (r:1 w:1)
    /// Proof: `Assets::Account` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
    fn block() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `375`
        //  Estimated: `3687`
        // Minimum execution time: 17_450_000 picoseconds.
        Weight::from_parts(17_877_000, 3687)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}
