name: Test Code

on:
  pull_request:
    branches:
    - develop
    - release/alphanet
    - release/devnet
    - release/testnet
    - release/mainnet
  push:
    branches:
    - develop
    - release/alphanet
    - release/devnet
    - release/testnet
    - release/mainnet

jobs:
  test-code:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install linux dependencies
      run: sudo apt-get install -y clang libssl-dev llvm libudev-dev protobuf-compiler

    - name: Install Rust
      run: |
        rustup update stable --no-self-update
        rustup target add wasm32-unknown-unknown

    # Rust cache
    - uses: Swatinem/rust-cache@v2

    # Enable this for clippy linting.
    # - name: Check and Lint Code
    #   run: cargo +nightly clippy -- -D warnings

    - name: Check Code
      run: cargo check

    - name: Test Code
      run: cargo test
